package store

import (
	"fmt"
)

// 存储 = PostgreSQL。迁移模型:单一 PG 基线 + 版本号。
//
// 为什么不是把 SQLite 时期的 14 步逐条 port:生产/测试库都是**整库搬运**(cmd/gwmigrate),
// 没有 PG 历史需要重放;faithfully 重建 m0011 的 LIKE 回填、m0014 的表重建只是无谓的churn。
// 故 baselinePG 直接建出「m0014 终态」的表结构,并把版本号播成 14 —— 使 SchemaVersion()
// ( /healthz 的 schema 字段)与升级脚本的降级护栏**语义不变**(后续 PG 迁移从 15 起追加)。
//
// 与 SQLite 时期的类型映射(刻意最小改动,见 DESIGN.md):
//   - 时间戳一律 text(UTC RFC3339Nano),不转 timestamptz —— 导入是逐列原样搬运;
//   - 布尔一律 bigint 0/1(b2i),不转 boolean —— 扫描侧不改成 *bool;
//   - JSON 一律 text(encodeJSON/decode*);
//   - 金额 REAL → double precision(**不用 numeric**:numeric 扫不进 *float64);
//   - 所有整数列一律 bigint(与 SQLite 的 64 位 INTEGER 对齐,且 pgx 回 int64);
//   - 自增主键 → bigint GENERATED BY DEFAULT AS IDENTITY(BY DEFAULT 以便导入显式 id,
//     导入后须 setval 推进序列 —— 见 cmd/gwmigrate)。
const schemaVersion = 14

// baselinePG 建出全部业务表(m0014 终态),外加索引。幂等由 schema_migrations 版本守卫
// + 单事务保证;DROP/建表均不带 IF EXISTS(SQLite 时期的半途兜底在新库已无必要)。
const baselinePG = `
CREATE TABLE admins (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username            text NOT NULL UNIQUE,
  password_bcrypt     text NOT NULL,
  role                text NOT NULL DEFAULT 'admin',
  balance_usd         double precision NOT NULL DEFAULT 0,
  rate_override       double precision,
  token_quota_ceiling double precision NOT NULL DEFAULT 0,
  token_rpm_ceiling   bigint NOT NULL DEFAULT 0,
  created_at          text NOT NULL
);

CREATE TABLE channels (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text NOT NULL UNIQUE,
  provider       text NOT NULL,
  base_url       text NOT NULL,
  api_key_cipher text NOT NULL DEFAULT '',
  key_masked     text NOT NULL DEFAULT '',
  priority       bigint NOT NULL DEFAULT 0,
  weight         bigint NOT NULL DEFAULT 0,
  timeout_ms     bigint NOT NULL DEFAULT 60000,
  tags           text NOT NULL DEFAULT '[]',
  enabled        bigint NOT NULL DEFAULT 1,
  max_failures   bigint NOT NULL DEFAULT 3,
  cooldown_sec   bigint NOT NULL DEFAULT 60,
  note           text NOT NULL DEFAULT '',
  channel_type   text NOT NULL DEFAULT '',
  egress_proto   text NOT NULL DEFAULT '',
  quota_path     text NOT NULL DEFAULT '',
  quota_shape    text NOT NULL DEFAULT '',
  created_at     text NOT NULL,
  updated_at     text NOT NULL
);

CREATE TABLE models (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                text NOT NULL UNIQUE,
  context_window      bigint NOT NULL DEFAULT 0,
  capabilities        text NOT NULL DEFAULT '[]',
  enabled             bigint NOT NULL DEFAULT 1,
  display_name        text NOT NULL DEFAULT '',
  official_vendor     text NOT NULL DEFAULT '',
  official_model_name text NOT NULL DEFAULT '',
  rate_override       double precision,
  created_at          text NOT NULL,
  updated_at          text NOT NULL
);
-- 已重命名的统一名唯一;未重命名的空串不参与约束(部分索引,PG 原样支持)。
CREATE UNIQUE INDEX idx_models_display_name ON models (display_name) WHERE display_name <> '';

CREATE TABLE model_offers (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id              bigint NOT NULL REFERENCES models(id)   ON DELETE CASCADE,
  channel_id            bigint NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  input_price_usd       double precision NOT NULL DEFAULT 0,
  output_price_usd      double precision NOT NULL DEFAULT 0,
  cache_read_price_usd  double precision NOT NULL DEFAULT 0,
  cache_write_price_usd double precision NOT NULL DEFAULT 0,
  override_price        bigint NOT NULL DEFAULT 0,
  priority              bigint NOT NULL DEFAULT 0,
  enabled               bigint NOT NULL DEFAULT 1,
  rate_limit_rpm        bigint NOT NULL DEFAULT 60,
  timeout_ms            bigint,
  note                  text NOT NULL DEFAULT '',
  price_source_url      text NOT NULL DEFAULT '',
  price_fetched_at      text NOT NULL DEFAULT '',
  price_currency        text NOT NULL DEFAULT '',
  price_native_text     text NOT NULL DEFAULT '',
  upstream_model        text NOT NULL DEFAULT '',
  UNIQUE (model_id, channel_id)
);

CREATE TABLE rules (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                text NOT NULL,
  enabled             bigint NOT NULL DEFAULT 1,
  match_mode          text NOT NULL,
  pattern             text NOT NULL,
  strategy            text NOT NULL,
  channel_ids         text NOT NULL DEFAULT '[]',
  weights             text,
  fallback_channel_id bigint,
  retry               bigint NOT NULL DEFAULT 1,
  timeout_ms          bigint NOT NULL DEFAULT 120000,
  sort                bigint NOT NULL DEFAULT 0,
  hit                 bigint NOT NULL DEFAULT 0,
  created_at          text NOT NULL,
  updated_at          text NOT NULL
);

CREATE TABLE tokens (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           text NOT NULL,
  sha256         text NOT NULL UNIQUE,
  key_masked     text NOT NULL,
  allowed_models text NOT NULL DEFAULT '[]',
  quota_usd      double precision NOT NULL DEFAULT 0,
  used_usd       double precision NOT NULL DEFAULT 0,
  rpm_limit      bigint NOT NULL DEFAULT 60,
  expires_at     text,
  status         text NOT NULL DEFAULT 'active',
  last_used_at   text,
  owner_id       bigint REFERENCES admins(id) ON DELETE CASCADE,
  key_cipher     text NOT NULL DEFAULT '',
  created_at     text NOT NULL,
  updated_at     text NOT NULL
);
CREATE INDEX idx_tokens_owner ON tokens (owner_id);

CREATE TABLE request_logs (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts                 text NOT NULL,
  model              text NOT NULL DEFAULT '',
  channel_id         bigint NOT NULL DEFAULT 0,
  channel_name       text NOT NULL DEFAULT '',
  token_id           bigint NOT NULL DEFAULT 0,
  token_name         text NOT NULL DEFAULT '',
  client_tool        text NOT NULL DEFAULT '',
  protocol           text NOT NULL DEFAULT '',
  stream             bigint NOT NULL DEFAULT 0,
  status             bigint NOT NULL DEFAULT 0,
  prompt_tokens      bigint NOT NULL DEFAULT 0,
  completion_tokens  bigint NOT NULL DEFAULT 0,
  cache_read_tokens  bigint NOT NULL DEFAULT 0,
  cache_write_tokens bigint NOT NULL DEFAULT 0,
  cost               double precision NOT NULL DEFAULT 0,
  charge_usd         double precision NOT NULL DEFAULT 0,
  owner_id           bigint NOT NULL DEFAULT 0,
  cost_source        text NOT NULL DEFAULT '',
  price_window       text NOT NULL DEFAULT '',
  first_token_ms     bigint NOT NULL DEFAULT 0,
  total_ms           bigint NOT NULL DEFAULT 0,
  ip                 text NOT NULL DEFAULT '',
  err                text
);
CREATE INDEX idx_logs_ts         ON request_logs (ts);
CREATE INDEX idx_logs_model      ON request_logs (model);
CREATE INDEX idx_logs_channel    ON request_logs (channel_name);
CREATE INDEX idx_logs_token      ON request_logs (token_name);
CREATE INDEX idx_logs_channel_id ON request_logs (channel_id);
CREATE INDEX idx_logs_token_id   ON request_logs (token_id);
CREATE INDEX idx_logs_owner      ON request_logs (owner_id, ts);

CREATE TABLE settings (
  k text PRIMARY KEY,
  v text NOT NULL
);

CREATE TABLE official_prices (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider          text NOT NULL,
  model_name        text NOT NULL,
  source            text NOT NULL DEFAULT 'commandcode',
  source_url        text NOT NULL,
  fetched_at        text NOT NULL,
  currency          text NOT NULL,
  billing_shape     text NOT NULL DEFAULT 'flat',
  in_price          double precision NOT NULL,
  out_price         double precision NOT NULL,
  cache_read_price  double precision NOT NULL DEFAULT 0,
  cache_write_price double precision NOT NULL DEFAULT 0,
  cache_derived     bigint NOT NULL DEFAULT 0,
  native_text       text NOT NULL DEFAULT '',
  detail_json       text NOT NULL DEFAULT '{}',
  content_sha256    text NOT NULL DEFAULT '',
  created_at        text NOT NULL,
  updated_at        text NOT NULL,
  UNIQUE (provider, model_name, source)
);
CREATE INDEX idx_official_prices_provider ON official_prices (provider);
CREATE INDEX idx_official_prices_source   ON official_prices (source);

CREATE TABLE channel_vendor_costs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_id bigint NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  vendor     text NOT NULL,
  ratio      double precision NOT NULL,
  note       text NOT NULL DEFAULT '',
  created_at text NOT NULL,
  updated_at text NOT NULL,
  UNIQUE (channel_id, vendor)
);
CREATE INDEX idx_channel_vendor_costs_channel ON channel_vendor_costs (channel_id);

CREATE TABLE announcements (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      text NOT NULL,
  body       text NOT NULL,
  level      text NOT NULL DEFAULT 'info',
  enabled    bigint NOT NULL DEFAULT 1,
  publish_at text,
  expires_at text,
  created_at text NOT NULL,
  updated_at text NOT NULL
);
CREATE INDEX idx_announcements_live ON announcements (enabled, publish_at, expires_at);

CREATE TABLE announcement_dismissals (
  announcement_id bigint NOT NULL REFERENCES announcements(id) ON DELETE CASCADE,
  admin_id        bigint NOT NULL REFERENCES admins(id)        ON DELETE CASCADE,
  dismissed_at    text NOT NULL,
  PRIMARY KEY (announcement_id, admin_id)
);

CREATE TABLE balance_logs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id      bigint NOT NULL REFERENCES admins(id) ON DELETE CASCADE,
  delta         double precision NOT NULL,
  balance_after double precision NOT NULL,
  reason        text NOT NULL,
  log_id        bigint NOT NULL DEFAULT 0,
  note          text NOT NULL DEFAULT '',
  created_at    text NOT NULL
);
CREATE INDEX idx_balance_logs_admin ON balance_logs (admin_id, id);
`

// migrate 建 schema_migrations,并在未应用当前基线时于单事务内建表 + 记录版本。
func migrate(db pdb) error {
	if _, err := db.Exec(`CREATE TABLE IF NOT EXISTS schema_migrations (
		version    bigint PRIMARY KEY,
		applied_at text NOT NULL
	)`); err != nil {
		return err
	}
	var n int
	if err := db.QueryRow(`SELECT COUNT(*) FROM schema_migrations WHERE version = ?`, schemaVersion).Scan(&n); err != nil {
		return err
	}
	if n > 0 {
		return nil
	}
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	if _, err := tx.Exec(baselinePG); err != nil {
		return fmt.Errorf("apply baseline: %w", err)
	}
	if _, err := tx.Exec(`INSERT INTO schema_migrations (version, applied_at) VALUES (?, ?)`,
		schemaVersion, nowRFC3339()); err != nil {
		return err
	}
	return tx.Commit()
}
